/**
 * Keyword lexicons for mapping paper abstracts to CS categories and methodology signals.
 */

export const CATEGORY_LEXICON: Record<string, string[]> = {
  "Artificial Intelligence": [
    "artificial intelligence",
    "agent",
    "multi-agent",
    "autonomous",
    "planning",
    "search algorithm",
    "heuristic",
    "knowledge representation",
    "reasoning",
    "ontology",
    "logic programming",
    "semantic web",
    "natural language processing",
    "nlp",
    "speech recognition",
    "dialogue system",
    "information extraction",
    "text generation",
    "computational linguistics",
    "sentiment analysis",
    "question answering",
    "named entity recognition",
    "machine translation",
    "large language model",
    "llm",
    "prompt engineering",
    "in-context learning",
    "retrieval augmented",
    "rag",
    "hallucination",
    "symbolic ai",
    "commonsense reasoning",
    "constraint satisfaction",
    "game playing",
    "expert system",
    "cognitive architecture",
    "neurosymbolic",
  ],
  "Machine Learning": [
    "machine learning",
    "deep learning",
    "neural network",
    "convolutional",
    "recurrent neural",
    "transformer",
    "attention mechanism",
    "diffusion model",
    "generative adversarial",
    "gan",
    "variational autoencoder",
    "vae",
    "reinforcement learning",
    "deep rl",
    "policy gradient",
    "q-learning",
    "markov decision process",
    "supervised learning",
    "unsupervised learning",
    "semi-supervised",
    "self-supervised",
    "few-shot",
    "zero-shot",
    "transfer learning",
    "fine-tuning",
    "lora",
    "peft",
    "overfitting",
    "regularization",
    "gradient descent",
    "optimization",
    "hyperparameter",
    "backpropagation",
    "representation learning",
    "embedding",
    "contrastive learning",
    "clustering",
    "classification",
    "regression",
    "federated learning",
    "meta-learning",
    "graph neural network",
    "gnn",
    "loss function",
  ],
  "Computer Vision & Multimedia": [
    "computer vision",
    "image classification",
    "object detection",
    "semantic segmentation",
    "instance segmentation",
    "image generation",
    "image processing",
    "video analysis",
    "action recognition",
    "face recognition",
    "optical flow",
    "pose estimation",
    "depth estimation",
    "3d reconstruction",
    "point cloud",
    "nerf",
    "neural radiance field",
    "gaussian splatting",
    "multimedia",
    "audio processing",
    "visual tracking",
    "scene understanding",
    "super resolution",
    "image retrieval",
    "feature extraction",
    "sift",
    "stereo vision",
    "lidar",
    "rgb-d",
    "generative vision",
    "video compression",
    "camera calibration",
    "medical imaging",
  ],
  "Cybersecurity & Privacy": [
    "cybersecurity",
    "security",
    "cryptography",
    "privacy",
    "differential privacy",
    "vulnerability",
    "exploit",
    "malware",
    "intrusion detection",
    "firewall",
    "adversarial attack",
    "trojan",
    "backdoor",
    "authentication",
    "authorization",
    "access control",
    "zero trust",
    "zero knowledge",
    "zk-proof",
    "homomorphic encryption",
    "secure multiparty",
    "threat modeling",
    "ransomware",
    "phishing",
    "side-channel",
    "hardware security",
    "network security",
    "web security",
    "smart contract security",
    "firmware",
    "reverse engineering",
    "fuzzing",
    "penetration testing",
    "forensics",
    "anonymity",
  ],
  "Data Management & Mining": [
    "data management",
    "database",
    "data mining",
    "big data",
    "data warehouse",
    "query processing",
    "query optimization",
    "indexing",
    "b-tree",
    "relational database",
    "nosql",
    "key-value store",
    "graph database",
    "vector database",
    "data stream",
    "streaming data",
    "data cleaning",
    "data integration",
    "entity resolution",
    "schema matching",
    "olap",
    "oltp",
    "distributed database",
    "transaction management",
    "concurrency control",
    "acid",
    "data governance",
    "data lineage",
    "pattern mining",
    "association rules",
    "spatial data",
    "temporal data",
    "recommender system",
  ],
  "Distributed Systems & Networks": [
    "distributed systems",
    "computer networks",
    "networking",
    "consensus",
    "paxos",
    "raft",
    "fault tolerance",
    "byzantine",
    "peer-to-peer",
    "p2p",
    "cloud computing",
    "edge computing",
    "serverless",
    "datacenter",
    "load balancing",
    "rpc",
    "microservices",
    "message queue",
    "routing protocol",
    "software-defined networking",
    "sdn",
    "5g",
    "6g",
    "wireless network",
    "sensor network",
    "internet of things",
    "iot",
    "tcp",
    "udp",
    "congestion control",
    "throughput",
    "latency",
    "bandwidth",
    "cellular network",
    "mesh network",
    "overlay network",
    "cluster computing",
  ],
  "Software Engineering & PL": [
    "software engineering",
    "programming languages",
    "compiler",
    "static analysis",
    "dynamic analysis",
    "symbolic execution",
    "software testing",
    "test generation",
    "unit test",
    "fuzzing",
    "debugging",
    "fault localization",
    "program repair",
    "automated repair",
    "code smell",
    "refactoring",
    "code generation",
    "program synthesis",
    "type system",
    "type inference",
    "formal verification",
    "model checking",
    "theorem proving",
    "version control",
    "git",
    "continuous integration",
    "ci/cd",
    "devops",
    "software maintenance",
    "repository mining",
    "api design",
    "microservices architecture",
    "open source",
    "empirical software engineering",
  ],
  "Human-Computer Interaction": [
    "human-computer interaction",
    "hci",
    "user experience",
    "ux",
    "user interface",
    "ui",
    "usability",
    "user study",
    "user-centered",
    "accessibility",
    "assistive technology",
    "wearable",
    "interaction design",
    "tangible interface",
    "gesture recognition",
    "eye tracking",
    "conversational agent",
    "human-ai interaction",
    "participatory design",
    "qualitative study",
    "interviews",
    "crowdsourcing",
    "social computing",
    "augmented reality",
    "virtual reality",
    "mixed reality",
    "ubiquitous computing",
    "ubicomp",
    "computer-supported collaborative",
    "cscw",
    "visualization",
    "information visualization",
  ],
  "Theory of Computation": [
    "theory of computation",
    "theoretical computer science",
    "algorithms",
    "computational complexity",
    "np-hard",
    "np-complete",
    "polynomial time",
    "approximation algorithm",
    "randomized algorithm",
    "graph algorithms",
    "spectral graph",
    "combinatorics",
    "discrete mathematics",
    "automata theory",
    "formal languages",
    "computational geometry",
    "cryptographic primitives",
    "information theory",
    "quantum computing",
    "quantum algorithm",
    "qubit",
    "quantum error correction",
    "algorithmic game theory",
    "mechanism design",
    "online algorithm",
    "streaming algorithm",
    "sublinear algorithm",
    "lower bound",
    "turing machine",
  ],
  "Graphics, VR & Games": [
    "computer graphics",
    "rendering",
    "ray tracing",
    "path tracing",
    "global illumination",
    "shader",
    "gpu",
    "mesh",
    "geometry processing",
    "animation",
    "character animation",
    "physics simulation",
    "fluid simulation",
    "cloth simulation",
    "virtual reality",
    "augmented reality",
    "haptics",
    "game design",
    "game development",
    "procedural generation",
    "real-time rendering",
    "texture mapping",
    "voxel",
  ],
  "Hardware & Architecture": [
    "computer architecture",
    "hardware",
    "microprocessor",
    "cpu",
    "gpu architecture",
    "tpu",
    "accelerator",
    "asic",
    "fpga",
    "system-on-chip",
    "soc",
    "embedded systems",
    "cache",
    "memory hierarchy",
    "dram",
    "nvram",
    "non-volatile memory",
    "interconnect",
    "vlsi",
    "chip design",
    "power efficiency",
    "thermal management",
    "approximate computing",
    "in-memory computing",
    "neuromorphic",
    "energy harvesting",
  ],
  "Information Systems": [
    "information systems",
    "information retrieval",
    "search engine",
    "web search",
    "relevance ranking",
    "bm25",
    "dense retrieval",
    "indexing",
    "digital library",
    "knowledge management",
    "enterprise systems",
    "business intelligence",
    "e-commerce",
    "collaborative filtering",
    "recommendation algorithm",
    "click-through rate",
    "evaluation metrics",
    "ndcg",
    "mean reciprocal rank",
  ],
  "Applied Computing": [
    "bioinformatics",
    "computational biology",
    "health informatics",
    "clinical data",
    "genomics",
    "proteomics",
    "cheminformatics",
    "smart grid",
    "computational social science",
    "digital humanities",
    "gis",
    "geographic information",
    "intelligent transportation",
    "smart cities",
    "educational technology",
    "e-learning",
    "financial technology",
    "fintech",
  ],
  "General & Interdisciplinary CS": [
    "interdisciplinary",
    "computational science",
    "scientific computing",
    "high-performance computing",
    "hpc",
    "parallel computing",
    "multidisciplinary",
    "cyber-physical systems",
    "complex systems",
    "simulation",
    "numerical methods",
  ],
};

export interface MethodologySignal {
  id: string;
  label: string;
  keywords: string[];
}

export const METHODOLOGY_SIGNALS: MethodologySignal[] = [
  {
    id: "empirical",
    label: "Empirical & Experimental",
    keywords: [
      "experiment",
      "empirical",
      "benchmark",
      "dataset",
      "baseline",
      "ablation",
      "evaluation",
      "measured",
      "outperformed",
      "state-of-the-art",
      "sota",
    ],
  },
  {
    id: "theory",
    label: "Theoretical & Mathematical",
    keywords: [
      "theorem",
      "proof",
      "lemma",
      "bound",
      "complexity",
      "asymptotic",
      "polynomial",
      "formal proof",
      "hardness",
    ],
  },
  {
    id: "user_study",
    label: "Human Subjects & User Study",
    keywords: [
      "user study",
      "participants",
      "interview",
      "survey",
      "usability testing",
      "qualitative",
      "likert",
      "human evaluation",
    ],
  },
  {
    id: "systems",
    label: "Systems & Implementation",
    keywords: [
      "implementation",
      "prototype",
      "throughput",
      "latency",
      "overhead",
      "runtime",
      "deployed",
      "scalability",
      "profiling",
      "end-to-end",
    ],
  },
  {
    id: "security_audit",
    label: "Security Audit & Attack Analysis",
    keywords: [
      "vulnerability",
      "exploit",
      "attack vector",
      "defense",
      "threat model",
      "countermeasure",
      "penetration",
      "cve",
    ],
  },
];

export const ENGLISH_STOPWORDS = new Set([
  "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are",
  "as", "at", "be", "because", "been", "before", "being", "below", "between", "both", "but",
  "by", "could", "did", "do", "does", "doing", "down", "during", "each", "few", "for", "from",
  "further", "had", "has", "have", "having", "he", "her", "here", "hers", "herself", "him",
  "himself", "his", "how", "i", "if", "in", "into", "is", "it", "its", "itself", "just", "me",
  "more", "most", "my", "myself", "no", "nor", "not", "now", "of", "off", "on", "once", "only",
  "or", "other", "our", "ours", "ourselves", "out", "over", "own", "same", "she", "should", "so",
  "some", "such", "than", "that", "the", "their", "theirs", "them", "themselves", "then",
  "there", "these", "they", "this", "those", "through", "to", "too", "under", "until", "up",
  "very", "was", "we", "were", "what", "when", "where", "which", "while", "who", "whom", "why",
  "with", "would", "you", "your", "yours", "yourself", "yourselves",
  // Academic generic stopwords:
  "paper", "propose", "proposed", "present", "presents", "presented", "study", "approach",
  "method", "methods", "result", "results", "show", "shows", "demonstrate", "demonstrates",
  "work", "novel", "new", "based", "using", "via", "well", "also", "including", "can",
  "provide", "provides", "article",
]);
